directories:
  output: release_builds
  buildResources: build
appId: com.davitec.app
productName: Davi.Tec
win:
  target: nsis
  icon: build/icon.ico
files:
  - filter:
      - dist/**/*
      - main.cjs
      - package.json
electronVersion: 44.4.3
