directories:
  output: dist_electron
  buildResources: build
appId: com.sampaio.cell
productName: Sampaio Cell
win:
  target: nsis
files:
  - filter:
      - dist/**/*
      - main.js
      - package.json
electronVersion: 44.4.3
